import time
import os
from colorama import Fore


while True:
        time.sleep(0.5)
        os.system("cls")
        print(Fore.GREEN+'                                                             ______')
        print(Fore.GREEN+'                                                          .-"      "-.')
        print(Fore.GREEN+'                                                         /            \\')
        print(Fore.GREEN+'                                             _          |              |          _')
        print(Fore.GREEN+'                                            ( \         |,  .-.  .-.  ,|         / )')
        print(Fore.GREEN+'                                             > "=._     | )(_*/  \*_)( |     _.=" <')
        print(Fore.GREEN+'                                            (_/"=._"=._ |/     /\     \| _.="_.="\_)')
        print(Fore.GREEN+'                                                   "=._ (_     ^^     _)"_.="')
        print(Fore.GREEN+'                                                       "=\__|IIIIII|__/="')
        print(Fore.GREEN+'                                                      _.="| \IIIIII/ |"=._')
        print(Fore.GREEN+'                                            _     _.="_.="\          /"=._"=._     _')
        print(Fore.GREEN+'                                           ( \_.="_.="     `--------`     "=._"=._/ )')
        print(Fore.GREEN+'                                            > _.="                            "=._ <')
        print(Fore.GREEN+'                                           (_/                                    \_)')
        print(Fore.GREEN, "                                                ALL YOUR BASE ARE BELONG TO US!")
        print(" ")
        print(Fore.GREEN, os.listdir())
        print(Fore.GREEN, os.getcwd())
        print(Fore.GREEN, "WANT YOUR BASE BACK? GO TO https://www.youtube.com/watch?v=dQw4w9WgXcQ  <")
        time.sleep(0.5)
        os.system("cls")
        print(Fore.GREEN+'                                                             ______')
        print(Fore.GREEN+'                                                          .-"      "-.')
        print(Fore.GREEN+'                                                         /            \\')
        print(Fore.GREEN+'                                             _          |              |          _')
        print(Fore.GREEN+'                                            ( \         |,  .-.  .-.  ,|         / )')
        print(Fore.GREEN+'                                             > "=._     | )(_*/  \*_)( |     _.=" <')
        print(Fore.GREEN+'                                            (_/"=._"=._ |/     /\     \| _.="_.="\_)')
        print(Fore.GREEN+'                                                   "=._ (_     ^^     _)"_.="')
        print(Fore.GREEN+'                                                       "=\__|IIIIII|__/="')
        print(Fore.GREEN+'                                                      _.="            "=._          ')
        print(Fore.GREEN+'                                            _     _.="_.="| \IIIIII/ |"=._"=._     _')
        print(Fore.GREEN+'                                           ( \_.="_.="    \          /    "=._"=._/ )')
        print(Fore.GREEN+'                                            > _.="         `--------`         "=._ < ')
        print(Fore.GREEN+'                                           (_/                                    \_)')
        print(Fore.GREEN, "                                                ALL YOUR BASE ARE BELONG TO US!")
        print(" ")
        print(Fore.GREEN, os.listdir())
        print(Fore.GREEN, os.getcwd())
        print(Fore.GREEN, "WANT YOUR BASE BACK? GO TO https://www.youtube.com/watch?v=dQw4w9WgXcQ <<")
        pass